# Generated by Django 5.2.4 on 2025-09-01 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('apelido', models.CharField(max_length=100, verbose_name='Apelido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('servico', models.CharField(blank=True, choices=[('contabilidade', 'Contabilidade'), ('consultoria', 'Consultoria Fiscal'), ('auditoria', 'Auditoria'), ('gestao', 'Gestão Empresarial'), ('outro', 'Outro')], max_length=50, verbose_name='Serviço de Interesse')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('concordo', models.BooleanField(default=False, verbose_name='Concordo com os termos')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
