# Generated by Django 5.2.5 on 2025-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={},
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='concordo',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='mensagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='servico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
