# Generated by Django 5.2.5 on 2025-11-15 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_alter_mensagem_options_remove_mensagem_apelido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='mensagem',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='servico',
            field=models.CharField(choices=[('Contabilidade', 'Contabilidade'), ('Consultoria Fiscal', 'Consultoria Fiscal'), ('Consultoria Financeira', 'Consultoria Financeira'), ('Auditoria', 'Auditoria'), ('Consultoria de Gestão Empresarial', 'Consultoria de Gestão Empresarial'), ('Controlo de Gestão', 'Controlo de Gestão'), ('Recursos Humanos', 'Recursos Humanos'), ('Serviços Administrativos', 'Serviços Administrativos'), ('Faturação', 'Faturação'), ('Outro', 'Outro')], max_length=100, verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
